### jekyll
# global
exclude: ['ruby', 'config.rb']
timezone: Europe/Paris
encoding: UTF-8
gems: [jekyll-less]
destination: /Volumes/Datas/prj/web/localhost/htdocs/mala_jekyll

### site
# general
name: MaLa
description: Carnets et notes
author: Jeff LANCE
email: jeff.lance@mala.fr
gitname: jefflance

relative_permalinks: true
permalink: /blog/:year/:month/:day/:title.html

# plugins
markdown: redcarpet
pygments: true
#lessc: /opt/local/bin/lessc	# deprecated since i use 'jekyll-less' gem

#gallerytag:
#    dir: images/galleries
#    url: /images/galleries
#    thumb_width: 150
#    thumb_height: 150
#    columns: 4

