# general
name: MaLa
description: Carnets et notes
author: Jeff LANCE
email: jeff.lance@mala.fr
gitname: jefflance

markdown: redcarpet
pygments: true
encoding: UTF-8
relative_permalinks: true
permalink: date

# plugins
gallerytag:
    dir: images/galleries
    url: /images/galleries
    thumb_width: 150
    thumb_height: 150
    columns: 4

lessc: /opt/local/bin/lessc --strict-imports
