### jekyll
# global
exclude: ['ruby', '*.pid']
timezone: Europe/Paris
encoding: UTF-8
gems: []

### site
# general
name: MaLa
description: Carnets et notes
author: Jeff LANCE
email: jeff.lance@mala.fr
gitname: jefflance

relative_permalinks: true
permalink: date

# plugins
markdown: redcarpet
pygments: true
lessc: /opt/local/bin/lessc

#gallerytag:
#    dir: images/galleries
#    url: /images/galleries
#    thumb_width: 150
#    thumb_height: 150
#    columns: 4

